---
title: "Multinomial Logistic Regression"
author: "Alexsandra Cavalcanti"
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output:
  html_document: null
  number_sections: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE, warning=FALSE}

if (require (readxl) == FALSE) {install.packages("readxl"); require (readxl)}
if (require (tidyverse) == FALSE) {install.packages("tidyverse"); require (tidyverse)}
if (require (nnet) == FALSE) {install.packages("nnet"); require (nnet)}
if (require (haven) == FALSE) {install.packages("haven"); require (haven)}
if (require (here) == FALSE) {install.packages("here"); require (here)}
if (require (ggeffects) == FALSE) {install.packages("ggeffects"); require (ggeffects)}
if (require (reshape2) == FALSE) {install.packages("reshape2"); require (reshape2)}
if(require(effects) == F) {install.packages("effects"); require(effects)}

```


# Goal:

> I am estimating the odds of choosing a particular training program according to income level and writing grades.

```{r}
ml <- read_dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")

ml <- ml %>% 
mutate_if(haven::is.labelled, haven::as_factor)

ml$prog <- relevel(ml$prog, ref = "academic")

program <- multinom(prog ~ ses + write, data = ml)

writep <- ggemmeans (program, term = c ("write", "ses"), x.as.factor = F) %>%
  as_tibble() %>%
  mutate (fit = plogis (predicted),
          LL = plogis(predicted - (1.96 * std.error)),
          UL = plogis(predicted + (1.96 * std.error))
          )

writep %>%
  ggplot(aes(x = x, y = fit, ymin = LL, ymax = UL, color = group, fill = group)) +
  geom_line () +
  geom_ribbon (alpha = .3)+
  facet_grid (response.level ~ .) +
  theme_minimal()

```

